[[section]]
name = "..ovl_En_Test4"
rom = 0x00EAB870
vram = 0x80A41D70
size = 0x1760

symbols = [
    { name = "D_80A43364", vram = 0x80A43364 },
    { name = "sCsIdList", vram = 0x80A434D0 },
]

[[section]]
name = "..ovl_En_Az"
rom = 0x00EFC060
vram = 0x80A94A30
size = 0x5450

symbols = [
    { name = "D_80AEF868", vram = 0x80A99010 },
]

[[section]]
name = "..ovl_En_GirlA"
rom = 0x00CDDC60
vram = 0x80863870
size = 0x1B00

symbols = [
    { name = "sShopItemEntries", vram = 0x80864A50 }
]

[[section]]
name = "..boot"
rom = 0x00001060
vram = 0x80080060
size = 0x194A0

symbols = [
    { name = "sReactionTextIds", vram = 0x801BC420}
]